"""baseline

Revision ID: 03bcd87f986c
Revises:
Create Date: 2026-05-26 20:43:58.542139

"""

import warnings
from typing import Any

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    FernetBackend,
    PasswordHash,
    StoredObject,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore


__all__ = [
    "data_downgrades",
    "data_upgrades",
    "downgrade",
    "schema_downgrades",
    "schema_upgrades",
    "upgrade",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = "03bcd87f986c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_types",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "id", name=op.f("pk_asset_types")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_asset_types_tenant_name"),
    )
    op.create_table(
        "event_log",
        sa.Column(
            "seq",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("hlc", sa.String(), nullable=False),
        sa.Column("schema_version", sa.BigInteger(), nullable=False),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("type_id", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("field_id", sa.String(), nullable=True),
        sa.Column(
            "op",
            sa.Enum("SET", "DELETE", name="eventop", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "value_json",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "received_at",
            sa.DateTimeUTC(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_event_log")),
        sa.UniqueConstraint("tenant_id", "hlc", name="uq_event_log_tenant_hlc"),
    )
    with op.batch_alter_table("event_log", schema=None) as batch_op:
        batch_op.create_index(
            "idx_event_log_tenant_seq", ["tenant_id", "seq"], unique=False
        )

    op.create_table(
        "maintenance_record_types",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "tenant_id", "id", name=op.f("pk_maintenance_record_types")
        ),
        sa.UniqueConstraint(
            "tenant_id", "name", name="uq_maintenance_record_types_tenant_name"
        ),
    )
    op.create_table(
        "schema_change_log",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("seq", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("command", sa.String(), nullable=False),
        sa.Column("entity_id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "payload",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "committed_at",
            sa.DateTimeUTC(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("tenant_id", "seq", name=op.f("pk_schema_change_log")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("session_id", name="uq_sessions_session_id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            "ix_sessions_session_id_unique", ["session_id"], unique=True
        )

    op.create_table(
        "tenants",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("disabled_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("disabled_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "asset_type_fields",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("parent_id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "data_type",
            sa.Enum(
                "TEXT",
                "NUMBER",
                "INTEGER",
                "BOOLEAN",
                "DATE",
                "DATETIME",
                name="fielddatatype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "validation",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_id"],
            ["asset_types.tenant_id", "asset_types.id"],
            name=op.f("fk_asset_type_fields_tenant_id_asset_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name=op.f("pk_asset_type_fields")),
        sa.UniqueConstraint(
            "tenant_id",
            "parent_id",
            "name",
            name="uq_asset_type_fields_tenant_type_name",
        ),
    )
    op.create_table(
        "assets",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("type_id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "properties",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("row_state_hlc", sa.String(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "type_id"],
            ["asset_types.tenant_id", "asset_types.id"],
            name=op.f("fk_assets_tenant_id_asset_types"),
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name=op.f("pk_assets")),
    )
    op.create_table(
        "maintenance_record_type_fields",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("parent_id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "data_type",
            sa.Enum(
                "TEXT",
                "NUMBER",
                "INTEGER",
                "BOOLEAN",
                "DATE",
                "DATETIME",
                name="fielddatatype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "validation",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_id"],
            ["maintenance_record_types.tenant_id", "maintenance_record_types.id"],
            name=op.f(
                "fk_maintenance_record_type_fields_tenant_id_maintenance_record_types"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "id", name=op.f("pk_maintenance_record_type_fields")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "parent_id",
            "name",
            name="uq_maintenance_record_type_fields_tenant_type_name",
        ),
    )
    op.create_table(
        "user_tenant_memberships",
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_user_tenant_memberships_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_tenant_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "tenant_id", name=op.f("pk_user_tenant_memberships")
        ),
        sa.UniqueConstraint("user_id", name="uq_user_tenant_memberships_user_id"),
    )
    op.create_table(
        "asset_field_values",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("asset_id", sa.GUID(length=16), nullable=False),
        sa.Column("field_id", sa.String(), nullable=False),
        sa.Column(
            "value_json",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("hlc", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "asset_id"],
            ["assets.tenant_id", "assets.id"],
            name=op.f("fk_asset_field_values_tenant_id_assets"),
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "asset_id", "field_id", name=op.f("pk_asset_field_values")
        ),
    )
    op.create_table(
        "maintenance_records",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("type_id", sa.GUID(length=16), nullable=False),
        sa.Column("asset_id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "properties",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("row_state_hlc", sa.String(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "asset_id"],
            ["assets.tenant_id", "assets.id"],
            name=op.f("fk_maintenance_records_tenant_id_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "type_id"],
            ["maintenance_record_types.tenant_id", "maintenance_record_types.id"],
            name=op.f("fk_maintenance_records_tenant_id_maintenance_record_types"),
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name=op.f("pk_maintenance_records")),
    )
    op.create_table(
        "maintenance_record_field_values",
        sa.Column("tenant_id", sa.GUID(length=16), nullable=False),
        sa.Column("maintenance_record_id", sa.GUID(length=16), nullable=False),
        sa.Column("field_id", sa.String(), nullable=False),
        sa.Column(
            "value_json",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("hlc", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "maintenance_record_id"],
            ["maintenance_records.tenant_id", "maintenance_records.id"],
            name=op.f(
                "fk_maintenance_record_field_values_tenant_id_maintenance_records"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id",
            "maintenance_record_id",
            "field_id",
            name=op.f("pk_maintenance_record_field_values"),
        ),
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maintenance_record_field_values")
    op.drop_table("maintenance_records")
    op.drop_table("asset_field_values")
    op.drop_table("user_tenant_memberships")
    op.drop_table("maintenance_record_type_fields")
    op.drop_table("assets")
    op.drop_table("asset_type_fields")
    op.drop_table("users")
    op.drop_table("tenants")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_session_id_unique")
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    op.drop_table("schema_change_log")
    op.drop_table("maintenance_record_types")
    with op.batch_alter_table("event_log", schema=None) as batch_op:
        batch_op.drop_index("idx_event_log_tenant_seq")

    op.drop_table("event_log")
    op.drop_table("asset_types")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
